import  pandas as pd
result = pd.read_csv('CityTemps.csv', delimiter = ',')
print(result)
result['Maximum'] = result[['Ludhiana','Amritsar','Chandigarh']].max(axis=1)
result['Minimum'] = result[['Ludhiana','Amritsar','Chandigarh']].min(axis=1)
print(result)
print("*****Maximum:*****")
print("Maximum Temparature of Ludhiana", result['Ludhiana'].max())
print("Maximum Temparature of Amritsar", result['Amritsar'].max())
print("Maximum Temparature of Chandigarh", result['Chandigarh'].max())
print("*****Minimum*****")
print("Minimum Temparature of Ludhiana", result['Ludhiana'].min())
print("Minimum Temparature of Amritsar", result['Amritsar'].min())
print("Minimum Temparature of Chandigarh", result['Chandigarh'].min())
print("=======================================================")
print(result.head())  # only the first 5 lines
print("=======================================================")
print(result.tail())    # the last few lines
print("=======================================================")
print(result.sample(5))   # a few random lines
print("=======================================================")
print(result[['Year' , 'Month']])   # Select specific columns
print("=======================================================")
print("*****YEAR 2014*****")
data1 = result[result.Year == 2014]
print(data1)
print("*****Maximum:*****")
print("Maximum Temparature of Ludhiana", data1['Ludhiana'].max())
print("Maximum Temparature of Amritsar", data1['Amritsar'].max())
print("Maximum Temparature of Chandigarh", data1['Chandigarh'].max())
print("*****Minimum*****")
print("Minimum Temparature of Ludhiana", data1['Ludhiana'].min())
print("Minimum Temparature of Amritsar", data1['Amritsar'].min())
print("Minimum Temparature of Chandigarh", data1['Chandigarh'].min())
print("*****Sorting*****")
sort_Ldh = data1.sort_values(['Ludhiana'], ascending=[True])
print(sort_Ldh)
sort_Amr = data1.sort_values(['Amritsar'], ascending=[True])
print(sort_Amr)
sort_Chd = data1.sort_values(['Chandigarh'], ascending=[True])
print(sort_Chd)
print("=======================================================")
print("*****YEAR 2015*****")
data2 = result[result.Year == 2015]
print(data2)
print("*****Maximum:*****")
print("Maximum Temparature of Ludhiana", data2['Ludhiana'].max())
print("Maximum Temparature of Amritsar", data2['Amritsar'].max())
print("Maximum Temparature of Chandigarh", data2['Chandigarh'].max())
print("*****Minimum*****")
print("Minimum Temparature of Ludhiana", data2['Ludhiana'].min())
print("Minimum Temparature of Amritsar", data2['Amritsar'].min())
print("Minimum Temparature of Chandigarh", data2['Chandigarh'].min())
sort_Ldh = data2.sort_values(['Ludhiana'], ascending=[True])
print(sort_Ldh)
sort_Amr = data2.sort_values(['Amritsar'], ascending=[True])
print(sort_Amr)
sort_Chd = data2.sort_values(['Chandigarh'], ascending=[True])
print(sort_Chd)
print("=======================================================")